import tensorflow as tf
import keras
import pathlib
import numpy as np
import pandas as pd
import os.path
import os
import time
import matplotlib.pyplot as plt
import sys, subprocess, pkgutil
if not pkgutil.find_loader("seaborn"):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "seaborn"])
import seaborn as sns

from datetime import datetime
from sklearn.model_selection import KFold
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.layers import RandomRotation, RandomFlip, RandomTranslation, RandomZoom, RandomBrightness
from tensorflow.keras.layers import Input, GlobalAveragePooling2D, Dropout, Dense, Lambda
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping, CSVLogger, ReduceLROnPlateau
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import CategoricalAccuracy, Precision, Recall

train_and_val_dir = pathlib.Path("train_and_val_datasets")
test_dir = pathlib.Path("test_dataset")
# artificial covid19 images generated by CycleGAN 
gan_dir = pathlib.Path("gan_dataset")

batch_size = 16
image_height = 224
image_width = 224
epochs = 20
fine_tune_epochs = 10
# options are "vgg16", "mobilenetv2" and "efficientnetb0"
model_name = "efficientnetb0" 
# options are "undersampling", "oversampling", "weighted_classes", "focal_loss" and "CycleGAN"
method_name = "CycleGAN"
AUTOTUNE = tf.data.AUTOTUNE
timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

MODEL_OPTIONS = {
    "vgg16": {
        "model": tf.keras.applications.VGG16,
        "preprocess": tf.keras.applications.vgg16.preprocess_input,
        "learning_rate": 1e-3,
        "fine_tuning_learning_rate": 1e-5,
        # Unfreeze whole block5 and last conv layer of block4
        "fine_tune_layers": ["block4_conv3", "block5_conv1", "block5_conv2", "block5_conv3"]
    },
    "mobilenetv2": {
        "model": tf.keras.applications.MobileNetV2,
        "preprocess": tf.keras.applications.mobilenet_v2.preprocess_input,
        "learning_rate": 2e-3,
        "fine_tuning_learning_rate": 1e-5,
        # Unfreeze block16 and block15
        "fine_tune_layers": ["block_15", "block_16", "Conv_1", "Conv_1_bn", "out_relu"]
    },
    "efficientnetb0": {
        "model": tf.keras.applications.EfficientNetB0,
        "preprocess": tf.keras.applications.efficientnet.preprocess_input,
        "learning_rate": 1e-3,
        "fine_tuning_learning_rate": 5e-5,
        # Unfreeze block7
        "fine_tune_layers": ["block7", "top_conv", "top_bn", "top_activation"]
    }
}

# Function for creating dataframe out of the directory
def build_dataframe(directory):
    filepaths = []
    labels = []

    for class_dir in directory.iterdir():
        if class_dir.is_dir():
            # directories names in train_and_val_dir are the class names
            label = class_dir.name
            for file in class_dir.glob("*.*"):
                # filepaths are the paths to the file eg. "train_and_val_datasets/no_findings/00011145_000.png"
                # labels are class names eg. "no_findings"
                filepaths.append(str(file))
                labels.append(label)
    
    df = pd.DataFrame({"filepath": filepaths, "label": labels})
    # converts the label column into a pandas categorical type 
    # eg. "0" for "covid19" class, "1" for "pneumonia" class and "3" for "no_findings" class
    df["label_index"] = df["label"].astype('category').cat.codes

    # converts each numerical label into a one-hot vector 
    # eg. "[1, 0, 0]" for "covid19" class, "[0, 1, 0]" for "pneumonia" class and "[0, 0, 1]" for "no_findings" class
    df["label_onehot"] = df["label_index"].apply(
        lambda x: tf.keras.utils.to_categorical(x, num_classes=len(df["label"].unique())))
    
    return df, df["label"].unique()

# Function for loading images
def load_image(path, label):
    image = tf.io.read_file(path)

    try: # JPEG decoding
        image = tf.image.decode_jpeg(image, channels=3, try_recover_truncated=True)
    except: # If JPEG decoding fails → try PNG decoding
        try:
            image = tf.image.decode_png(image, channels=3)
        except: # If both fail → return a black image
            image = tf.zeros([*(image_height, image_width), 3], dtype=tf.uint8)

    # resize the image to image_height x image_width
    image = tf.image.resize(image, [image_height, image_width], method="nearest")
    return image, label

# Function for creating dataset from dataframe
def df_to_dataset(df, shuffle=True):
    paths = df["filepath"].values
    labels = np.stack(df["label_onehot"].values)
    ds = tf.data.Dataset.from_tensor_slices((paths, labels))

    if shuffle:
        ds = ds.shuffle(len(df))

    # loading the images to dataset and resizing them
    ds = ds.map(lambda x, y: load_image(x, y), num_parallel_calls=AUTOTUNE)

    # prefetch() tells TensorFlow to prepare the next batch in the background while the model is training on the current batch
    # tf.data.AUTOTUNE means: TensorFlow, you decide how many batches to prepare ahead of time.
    ds = ds.batch(batch_size).prefetch(AUTOTUNE)
    return ds

# Function for data augmentation
data_augmentation = tf.keras.Sequential([
    # RandomRotation(0.1),
    RandomRotation(10/360),
    # RandomTranslation(height_factor=0.1, width_factor=0.1), # more aggressive
    # RandomZoom(height_factor=0.1, width_factor=0.1), # more aggressive
    # RandomBrightness(factor=0.2, value_range=(0, 1)),
    RandomFlip(mode="horizontal")
])

# More aggressive version of data augmentation
# data_augmentation = tf.keras.Sequential([
#     RandomFlip("horizontal"),
#     RandomRotation(0.1),
#     RandomZoom(0.1),
#     RandomTranslation(height_factor=0.1, width_factor=0.1) 
# ])

# Function for creating the CNN model
# version of build_model function when focal loss was implemented
# def build_model(num_classes, model_name, loss): 
def build_model(num_classes, model_name):   
    if model_name not in MODEL_OPTIONS:
        raise ValueError(f"❌ Unsupported model: {model_name}")

    # data preprocessing
    inputs = Input(shape=(image_height, image_width, 3))
    x = data_augmentation(inputs)
    preprocess_input = MODEL_OPTIONS[model_name]["preprocess"]
    # preprocessing becomes an actual Keras layer in the model graph
    x = Lambda(preprocess_input, name="preprocessing_layer")(x)

    # pretrained cnn
    base_model = MODEL_OPTIONS[model_name]["model"](include_top=False, weights="imagenet", input_tensor=x)
    base_model.trainable = False
    # base_model.summary()

    # new classifier
    x=base_model.output
    x = GlobalAveragePooling2D()(x)
    x = Dense(128, activation="relu")(x)
    x = Dropout(0.5)(x)
    outputs = Dense(num_classes, activation='softmax')(x)

    model = Model(inputs, outputs)
    # model.summary()

    metrics = [
        CategoricalAccuracy(name='accuracy'),
        Precision(name='precision'),
        Recall(name='recall')
    ]

    model.compile(optimizer=Adam(learning_rate=MODEL_OPTIONS[model_name]["learning_rate"]),
                  loss=CategoricalCrossentropy(),
                  # used for focal loss implementation
                  # loss=loss,
                  metrics=metrics)

    # initial loss and accuracy
    # loss0, accuracy0 = model.evaluate(validation_dataset)
    # print("initial loss: {:.2f}".format(loss0))
    # print("initial accuracy: {:.2f}".format(accuracy0))

    return model, base_model

# Function for saving the confusion matrix
def save_confusion_matrix(y_true, y_pred, class_names, fold):
    # Make sure directory exists
    out_dir = "acc+loss"
    os.makedirs(out_dir, exist_ok=True)

    cm = confusion_matrix(y_true, y_pred)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names,
                yticklabels=class_names)
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title(f"Confusion Matrix - Fold {fold}")
    
    plt.tight_layout()
    plt.savefig(f"{out_dir}/confusion_matrix_fold_{fold}.png")
    plt.close()

# Function for saving the acc and loss plots
def save_plots(history_shallow, history_fine, name):
    # Make sure directory exists
    out_dir = "acc+loss"
    os.makedirs(out_dir, exist_ok=True)

    # Extract metrics
    acc_shallow = history_shallow.history['accuracy']
    val_acc_shallow = history_shallow.history['val_accuracy']
    loss_shallow= history_shallow.history['loss']
    val_loss_shallow = history_shallow.history['val_loss']

    acc_fine = history_fine.history['accuracy']
    val_acc_fine = history_fine.history['val_accuracy']
    loss_fine = history_fine.history['loss']
    val_loss_fine = history_fine.history['val_loss']

    # Combine
    acc = acc_shallow + acc_fine
    val_acc = val_acc_shallow + val_acc_fine
    loss = loss_shallow + loss_fine
    val_loss = val_loss_shallow + val_loss_fine

    # Index where fine-tuning starts
    start_ft = len(acc_shallow) - 1  # use minus 1 because epochs start at 0


    # Plot accuracy
    plt.figure(figsize=(10, 6))
    plt.plot(acc, label='Train Accuracy', marker='o')
    plt.plot(val_acc, label='Val Accuracy', marker='o')

    # Add vertical line
    plt.axvline(start_ft, linestyle='--', color='red', label='Fine-tuning Start')

    plt.title(f"Accuracy - {name}")
    plt.xlabel("Epochs")
    plt.ylabel("Accuracy")
    plt.legend()
    plt.grid(True)
    plt.savefig(f"{out_dir}/accuracy_{name}.png", dpi=210)
    plt.close()

    # Plot loss
    plt.figure(figsize=(10, 6))
    plt.plot(loss, label='Train Loss', marker='o')
    plt.plot(val_loss, label='Val Loss', marker='o')

    plt.axvline(start_ft, linestyle='--', color='red', label='Fine-tuning Start')

    plt.title(f"Loss - {name}")
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True)
    plt.savefig(f"{out_dir}/loss_{name}.png", dpi=210)
    plt.close()

# implementation of the 5-fold cross validation
# version of the function when CycleGAN artifical images are applied
# def run_5fold_cross_validation(df, class_names, model_name, df_gan):
def run_5fold_cross_validation(df, class_names, model_name):
    if model_name not in MODEL_OPTIONS:
        raise ValueError(f"❌ Unsupported model: {model_name}")
    
    kf = KFold(n_splits=5, shuffle=True, random_state=123)
    val_accuracy_list = []
    recall_list = []
    precision_list = []
    f1_score_list = []
    f1_across_folds = []

    for fold, (train_idx, val_idx) in enumerate(kf.split(df)):
        print(f"\n==================== FOLD {fold} ====================\n")

        train_df = df.iloc[train_idx]
        val_df = df.iloc[val_idx]

        # class weights approach
        # class_weights = get_class_weights(train_df, class_names)
        # print(f"Class weights fold {fold}: ", class_weights)

        # calculating alpha for focal loss approach
        # alpha = compute_alpha(train_df, class_names)
        # print(f"Alpha value fold {fold}: ", alpha)
        
        # undersampling approach
        # print("Train set BEFORE undersampling:")
        # print(train_df["label"].value_counts())
        # print("Total:", len(train_df))
        # train_df = undersampling(train_df)
        # print("Train set AFTER resampling:")
        # print(train_df["label"].value_counts())
        # print("Total:", len(train_df))

        # oversampling approach
        # print("Train set BEFORE oversampling:")
        # print(train_df["label"].value_counts())
        # print("Total:", len(train_df))
        # train_df = oversampling(train_df)
        # print("Train set AFTER oversampling:")
        # print(train_df["label"].value_counts())
        # print("Total:", len(train_df))

        # CycleGAN approach
        # print("Train images before gan:", len(train_df))
        # print("Classes: ", classes)
        # print("Number of loaded images per class: ", train_df["label"].value_counts())
        # train_df = pd.concat([train_df, df_gan], ignore_index=True)
        # print("Train images after gan:", len(train_df))
        # print("Classes: ", classes)
        # print("Number of loaded images per class: ", train_df["label"].value_counts())

        train_ds = df_to_dataset(train_df, shuffle=True)
        val_ds = df_to_dataset(val_df, shuffle=False)

        # Shallow tunning -------------------------------------------------------------------------------

        # focal loss approach
        # focal_loss = categorical_focal_loss(alpha=alpha, gamma=2.0)
        # model, base_model = build_model(num_classes=len(class_names), model_name=model_name, loss=focal_loss)

        model, base_model = build_model(num_classes=len(class_names), model_name=model_name)

        shallowTunningCallbacks = [
            # ModelCheckpoint(filepath=f"models/checkpoints/fold_{fold}_{model_name}_shallow_tunning_best.keras",
            #     monitor="val_loss", verbose=1, save_best_only=True),
            # CSVLogger(os.path.join('models','logs',f"{model_name}_shallow_tunning_fold_{fold}-{timestamp}.log")),
            EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True, verbose=1),
            ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-7, verbose=1)
        ]

        history_shallow = model.fit(train_ds, 
                                    epochs=epochs, 
                                    validation_data=val_ds,
                                    callbacks=shallowTunningCallbacks, 
                                    # used for class weights approach
                                    # class_weight=class_weights
        )

        # Fine tunning ----------------------------------------------------------------------------------
        for layer in base_model.layers:
            # Unfreeze base_model layers for fine tunning
            if layer.name in MODEL_OPTIONS[model_name]["fine_tune_layers"]:
                layer.trainable = True
            else:
                layer.trainable = False

            # Keep BatchNormalization layers frozen
            if isinstance(layer, tf.keras.layers.BatchNormalization):
                layer.trainable = False
        
        metrics = [
            CategoricalAccuracy(name='accuracy'),
            Recall(name='recall'),
            Precision(name='precision')
        ]

        model.compile(
            optimizer=Adam(learning_rate=MODEL_OPTIONS[model_name]["fine_tuning_learning_rate"]),
            loss=CategoricalCrossentropy(),
            # used for focal loss approach
            # loss=focal_loss,
            metrics=metrics)
        
        fineTunningCallbacks = [
            # ModelCheckpoint(filepath=f"models/checkpoints/fold_{fold}_{model_name}_fine_tunning_best.keras",
            #     monitor="val_loss", verbose=1, save_best_only=True),
            # CSVLogger(os.path.join('models','logs',f"{model_name}_fine_tunning_fold_{fold}-{timestamp}.log"))
            EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True, verbose=1),
            ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=5e-6, verbose=1)
        ]

        history_fine = model.fit(train_ds, 
                                 epochs=fine_tune_epochs, 
                                 validation_data=val_ds,
                                 callbacks=fineTunningCallbacks,
                                 # used for class weights approach
                                 # class_weight=class_weights
        )
        
        # Get true labels and predictions
        y_true = np.concatenate([y for x, y in val_ds], axis=0)
        y_true = np.argmax(y_true, axis=1)

        y_pred = model.predict(val_ds)
        y_pred = np.argmax(y_pred, axis=1)

        # Per-class F1 score
        f1_per_class = f1_score(y_true, y_pred, average=None)
        print(f"Class Names: {class_names}")
        print(f"F1 per class: {f1_per_class}")

        # Macro-F1 (average of classes)
        f1_macro = f1_score(y_true, y_pred, average="macro")
        print(f"F1 Macro: {f1_macro}")
        
        # Save training plots and confusion matrix for this fold
        save_plots(history_shallow, history_fine, f"fold_{fold}")
        save_confusion_matrix(y_true, y_pred, class_names, fold)
   
        loss, acc, rec, prec = model.evaluate(val_ds, verbose=0)
        val_accuracy_list.append(acc)
        recall_list.append(rec)
        precision_list.append(prec)
        f1_score_list.append(f1_macro)
        f1_across_folds.append(f1_per_class)

    
    # Print cross-validation metrics
    print("Validation metrics for: ", model_name.upper(), "-", method_name,
          " learning_rate=", MODEL_OPTIONS[model_name]["learning_rate"],
          " fine_tuning_learning_rate=", MODEL_OPTIONS[model_name]["fine_tuning_learning_rate"])
    print("Fold accuracies:", val_accuracy_list)
    print("Mean accuracy:", np.mean(val_accuracy_list))
    print("Std deviation:", np.std(val_accuracy_list))

    print("Fold recalls:", recall_list)
    print("Mean recall:", np.mean(recall_list))
    print("Std deviation:", np.std(recall_list))

    print("Fold precisions:", precision_list)
    print("Mean precision:", np.mean(precision_list))
    print("Std deviation:", np.std(precision_list))

    f1_across_folds = np.array(f1_across_folds)
    mean_f1_per_class = np.mean(f1_across_folds, axis=0)
    print("Mean F1 per class across all folds:", mean_f1_per_class)

    print("Mean F1 Macro:", np.mean(f1_score_list))
    print("Std F1 Macro:", np.std(f1_score_list))

# function for applying undersampling on a dataFrame
def undersampling(train_df, factor=3, random_state=42):
    class_counts = train_df["label"].value_counts()
    min_count = class_counts.min()
    df_list = []

    for cls, count in class_counts.items():
        # splitting the training dataFrame based on unique class labels values
        cls_df = train_df[train_df["label"] == cls]
        if count > min_count:
            # calculating the new number of samples that is 3x smaller than the original
            target_size = max(min_count, count // factor)
            # randomly selecting target_size samples from the majority classes
            cls_df = cls_df.sample(n=target_size, replace=False, random_state=random_state)

        df_list.append(cls_df)

    # combine three new dataFrames back into one
    undersampled_df = pd.concat(df_list).sample(frac=1, random_state=random_state).reset_index(drop=True)
    return undersampled_df

# function for applying oversampling on a dataFrame
def oversampling(train_df, factor=3, random_state=42):
    class_counts = train_df["label"].value_counts()
    max_count = class_counts.max()
    min_count = class_counts.min()
    df_list = []

    for cls, count in class_counts.items():
        # splitting the training dataFrame based on unique class labels values
        cls_df = train_df[train_df["label"] == cls]
        if count == min_count:
            # calculating the new number of samples that is 3x larger than the original
            target_size = min(max_count, count * factor)
            # randomly duplicating target_size samples for the minority class
            cls_df = cls_df.sample(n=target_size, replace=True, random_state=random_state)

        df_list.append(cls_df)

    # combine three new dataFrames back into one
    oversampled_df = pd.concat(df_list).sample(frac=1, random_state=random_state).reset_index(drop=True)
    return oversampled_df

# function for calculating class weights
def get_class_weights(df, class_names, label_col="label"):
    y = df[label_col].values
    class_weights = compute_class_weight(class_weight="balanced", 
                                         classes=np.array(class_names), 
                                         y=y)
    class_weight_dictionary = {i: w for i, w in enumerate(class_weights)}
    return class_weight_dictionary

# function for calculating alpha parameter of focal loss
def compute_alpha(df, class_names, label_col="label"):
    y = df[label_col].values
    class_weights = compute_class_weight(class_weight="balanced", 
                                         classes=np.array(class_names), 
                                         y=y)
    alpha = tf.constant(class_weights, dtype=tf.float32)
    return alpha

# function for defining focal loss
def categorical_focal_loss(alpha, gamma=2.0):
    def loss(y_true, y_pred):
        y_pred = tf.clip_by_value(y_pred, 1e-7, 1 - 1e-7)
        # focal loss formula
        focal_loos = -alpha * y_true * tf.pow(1 - y_pred, gamma) * tf.math.log(y_pred)
        return tf.reduce_sum(focal_loos, axis=1)
    return loss

df_unbalanced, classes = build_dataframe(train_and_val_dir)
print("Original dataset:")
print("Number of loaded images: ", len(df_unbalanced))
print("Classes: ", classes)
print("Number of loaded images per class: ", df_unbalanced["label"].value_counts())

# CycleGAN approach
# df_gan, _ = build_dataframe(gan_dir)
# df_gan["label_index"] = df_gan["label"].apply(lambda x: list(classes).index(x))
# df_gan["label_onehot"] = df_gan["label_index"].apply(lambda x: tf.keras.utils.to_categorical(x, num_classes=len(classes)))
# print("Original gan dataset:")
# print("Number of loaded images: ", len(df_gan))
# folder_classes = [p.name for p in gan_dir.iterdir() if p.is_dir()]
# print("GAN folder classes:", folder_classes)
# print("GAN df classes (present):", df_gan["label"].unique())
# print("Number of loaded images per class: ", df_gan["label"].value_counts())

# function run_5fold_cross_validation call when applying CycleGAN approach
# run_5fold_cross_validation(df=df_unbalanced, class_names=classes, model_name=model_name, df_gan=df_gan)
run_5fold_cross_validation(df=df_unbalanced, class_names=classes, model_name=model_name)

# function for calculating test metric and printing confusion matrix
def evaluate_test_set(model, test_ds, class_names, folder="acc+loss"):
    import os
    os.makedirs(folder, exist_ok=True)

    # === TRUE LABELS ===
    y_true = np.concatenate([y for x, y in test_ds], axis=0)
    y_true = np.argmax(y_true, axis=1)

    # === PREDICTIONS ===
    y_pred = np.argmax(model.predict(test_ds), axis=1)

    # === CONFUSION MATRIX ===
    cm = confusion_matrix(y_true, y_pred)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=class_names, yticklabels=class_names)
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.title("Confusion Matrix (Test Set)")

    plt.tight_layout()
    plt.savefig(f"{folder}/test_confusion_matrix.png")
    plt.close()

    # === METRICS ===
    accuracy = accuracy_score(y_true, y_pred)
    f1_per_class = f1_score(y_true, y_pred, average=None)
    f1_macro = f1_score(y_true, y_pred, average="macro")
    precision = precision_score(y_true, y_pred, average=None)
    recall = recall_score(y_true, y_pred, average=None)

    return accuracy, f1_per_class, f1_macro, precision, recall

# FINAL MODEL ---------------------------------------------------------------------------
# Create datasets allocating 80% for training and 20% for validation
df_final = df_unbalanced.sample(frac=1, random_state=123).reset_index(drop=True)
split_index = int(len(df_final) * 0.8)
train_df = df_final.iloc[:split_index]
val_df   = df_final.iloc[split_index:]
print("Train images:", len(train_df))
print("Validation images:", len(val_df))

# class weights approach
# class_weights = get_class_weights(train_df, classes)
# print("Class weights final model: ", class_weights)

# calculating alpha for focal loss approach
# alpha = compute_alpha(train_df, classes)
# print("Alpha value final model: ", alpha)

# undersampling approach
# print("Train images before undersampling:", len(train_df))
# train_df = undersampling(train_df)
# print("Train images after undersampling:", len(train_df))

# oversampling approach
# print("Train images before oversampling:", len(train_df))
# print("Classes: ", classes)
# print("Number of loaded images per class: ", train_df["label"].value_counts())
# train_df = oversampling(train_df)
# print("Train images after oversampling:", len(train_df))
# print("Classes: ", classes)
# print("Number of loaded images per class: ", train_df["label"].value_counts())

# CycleGAN approach
# print("Train images before gan:", len(train_df))
# print("Classes: ", classes)
# print("Number of loaded images per class: ", train_df["label"].value_counts())
# train_df = pd.concat([train_df, df_gan], ignore_index=True)
# print("Train images after gan:", len(train_df))
# print("Classes: ", classes)
# print("Number of loaded images per class: ", train_df["label"].value_counts())

train_dataset = df_to_dataset(train_df, shuffle=True)
validation_dataset   = df_to_dataset(val_df, shuffle=False)

start_time = time.time()

# focal loss approach
# focal_loss = categorical_focal_loss(alpha=alpha, gamma=2.0)
# model, base_model = build_model(num_classes=len(classes), model_name=model_name, loss=focal_loss)

model, base_model = build_model(num_classes=len(classes), model_name=model_name)

shallowTunningCallbacks = [
    # ModelCheckpoint(filepath=f"models/checkpoints/final_{model_name}_shallow_tunning_best.keras",
    #     monitor="val_loss", verbose=1, save_best_only=True),
    # CSVLogger(os.path.join('models','logs',f"{model_name}_shallow_tunning_final-{timestamp}.log")),
    EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=2, min_lr=1e-7, verbose=1)
]

shallow_history = model.fit(train_dataset,
                    epochs=epochs,
                    validation_data=validation_dataset,
                    callbacks=shallowTunningCallbacks,
                    # used for class weight approach
                    # class_weight=class_weights
)

# Fine tunning
for layer in base_model.layers:
    # Unfreeze base_model layers for fine tunning
    if layer.name in MODEL_OPTIONS[model_name]["fine_tune_layers"]:
        layer.trainable = True
    else:
        layer.trainable = False

    # Keep BatchNormalization layers frozen
    if isinstance(layer, tf.keras.layers.BatchNormalization):
        layer.trainable = False

metrics = [
    CategoricalAccuracy(name='accuracy'),
    Recall(name='recall'),
    Precision(name='precision')
]

model.compile(
    optimizer=Adam(learning_rate=MODEL_OPTIONS[model_name]["fine_tuning_learning_rate"]),
    loss=CategoricalCrossentropy(),
    # used for focal loss approach
    # loss=focal_loss,
    metrics=metrics)

fineTunningCallbacks = [
    ModelCheckpoint(filepath=f"models/final_checkpoints/final_{model_name}_{method_name}_fine_tunning_best.keras",
        monitor="val_loss", verbose=1, save_best_only=True),
    CSVLogger(os.path.join('models','logs',f"{model_name}_{method_name}_fine_tunning_final-{timestamp}.log")),
    EarlyStopping(monitor="val_loss", patience=5, restore_best_weights=True, verbose=1),
    ReduceLROnPlateau(monitor='val_loss', factor=0.2, patience=3, min_lr=5e-6, verbose=1)
]

history = model.fit(train_dataset, 
                    epochs=fine_tune_epochs, 
                    validation_data=validation_dataset,
                    callbacks=fineTunningCallbacks,
                    # used for class weights approach
                    # class_weight=class_weights
)

end_time = time.time()

training_time = end_time - start_time
print(f"\nTotal final model training time: {training_time/60:.2f} minutes")

# Get true labels and predictions
y_true = np.concatenate([y for x, y in validation_dataset], axis=0)
y_true = np.argmax(y_true, axis=1)

y_pred = model.predict(validation_dataset)
y_pred = np.argmax(y_pred, axis=1)

# Per-class F1 score
f1_per_class = f1_score(y_true, y_pred, average=None)
print(f"Class Names: {classes}")
print(f"F1 per class: {f1_per_class}")

# Macro-F1 (average of classes)
f1_macro = f1_score(y_true, y_pred, average="macro")
print(f"F1 Macro: {f1_macro}")

# Save training plots and confusion matrix for final model
save_plots(shallow_history, history, "final")

print("Validation metrics for final: ", model_name.upper(), "-", method_name,
        " learning_rate=", MODEL_OPTIONS[model_name]["learning_rate"],
        " fine_tuning_learning_rate=", MODEL_OPTIONS[model_name]["fine_tuning_learning_rate"])

loss, acc, rec, prec = model.evaluate(validation_dataset, verbose=0)
print("Validation accuracy:", acc)
print("Validation recall:", rec)
print("Validation precision:", prec)
print("Validation F1 macro:", f1_macro)

# FINAL MODEL TESTING---------------------------------------------------------------------------
test_df, classes = build_dataframe(test_dir)
print("Number of loaded images: ", len(test_df))
print("Classes: ", classes)
print("Number of loaded images per class: ", test_df["label"].value_counts())

test_ds = df_to_dataset(test_df, shuffle=False)
# model.evaluate(test_ds)

acc, f1, f1_macro, prec, rec = evaluate_test_set(model, test_ds, classes)

print("\n===== FINAL TEST RESULTS =====")
print("Accuracy:", acc)
print("Classes:", classes)
print("F1 per class:", f1)
print("Macro F1:", f1_macro)
print("Precision:", prec)
print("Mean precision:", np.mean(prec))
print("Std deviation:", np.std(prec))
print("Recall:", rec)
print("Mean recall:", np.mean(rec))
print("Std deviation:", np.std(rec))
